# Generated by Django 3.1.3 on 2021-03-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoughts', models.TextField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, max_length=50, null=True)),
                ('skillper', models.IntegerField(blank=True, default='', null=True)),
                ('art_images', models.ImageField(blank=True, null=True, upload_to='shop/pics')),
                ('img_desc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PythonProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('projectsDesc', models.TextField()),
                ('projectlink', models.CharField(max_length=100)),
                ('projectOutput', models.ImageField(blank=True, null=True, upload_to='shop/pics')),
            ],
        ),
    ]
